# Generated by Django 3.2.9 on 2021-11-16 21:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('type', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_phone', models.IntegerField()),
            ],
        ),
    ]
